services:
  - type: web
    name: kebayaku
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: Production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:nboe3/mKjKlDksbTkwji3InJ87d4Ixsw3/SVVlvecTY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_kebaya
      - key: DB_USERNAME
        value: freedb_kebaya
      - key: DB_PASSWORD
        value: YCr*M?*jk6vAA9Q
      - key: APP_URL
        value: https://kebayaku.onrender.com
